<?php
	// ========================================================================================
	// EMAIL HEADING
	// ======================================================================================== 
	$email_start =  "<!DOCTYPE html>
	<html lang='en'>
  	<head>
	    <meta charset='utf-8'>
	    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
	    <meta name='viewport' content='width=device-width, initial-scale=1'>
	    <title>Additional Pay Request::Facilities and Services::University of Rochester</title>
	</head>
	<body>
	This is an automated message generated by the Facilities 'Additional Pay Request' form.<br/> 
	Below is a summary of the request.<br/><br/>";
	
	// ========================================================================================
	// EMAIL BODY - INCLUDES SANITIZED FORM CONTENT
	// ======================================================================================== 
	$email_body = "<table border='0' cellspacing='6' cellpadding='0'>
		<tr><th colspan='2' style='text-align:left;'>REQUESTER INFO</th></tr>
		<tr>
			<td ><strong>Requester:</strong></td>
			<td >" . $form_data['requester_fname'] . " " . $form_data['requester_lname'] . "</td>
		</tr>
			<td ><strong>Phone:</strong></td>
			<td >" . $form_data['phone_number'] . "</td>
		</tr>		
		<tr style='background-color:gray;'><td colspan='2'>&nbsp;<!-- spacer -->&nbsp;</td></tr>

		<tr><th colspan='2' style='text-align:left;'>EMPLOYEE</th></tr>
		<tr>
			<td ><strong>Employee:</strong></td>
			<td >" . $form_data['emp_fname'] . " " . $form_data['emp_lname'] . "</td>
		</tr>
		<tr>
			<td ><strong>Department:</strong></td>
			<td >" . $department . "</td>
		</tr>
		<tr>
			<td ><strong>Dept Phone:</strong></td>
			<td >" . $form_data['dept_phone'] . "</td>
		</tr>
		<tr style='background-color:gray;'><td colspan='2'>&nbsp;<!-- spacer -->&nbsp;</td></tr>

		<tr><th colspan='2' style='text-align:left;'>WORK PERFORMED</th></tr>				
		<tr>
			<td ><strong>Reason for Payment:</strong></td>
			<td >" . $form_data['reason'] .  "</td>
		</tr>
		<tr>
			<td ><strong>Work Start Date:</strong></td>
			<td >" . $form_data['start_date'] . "</td>
		</tr>
		<tr>
			<td ><strong>Work End Date:</strong></td>
			<td >" . $form_data['end_date'] . "</td>
		</tr>
		<tr>
			<td ><strong>Job Title:</strong></td>
			<td >" . $form_data['job_title'] . "</td>
		</tr>
		<tr>
			<td ><strong>Work Description:</strong></td>
			<td >" . $form_data['work_description'] . "</td>
		</tr>
		<tr>
			<td ><strong>Work Class:</strong></td>
			<td >" . $form_data['work_class'] . "</td>
		</tr>";
if($who == 'admin') {		
		$email_body .= "<tr style='background-color:gray;'><td colspan='2'>&nbsp;<!-- spacer -->&nbsp;</td></tr>
		<tr><th colspan='2' style='text-align:left;'>ADMINISTRATIVE</th></tr>
		<tr>
			<td ><strong>Employee ID:</strong></td>
			<td >" . $form_data['emp_ID'] ."</td>
		</tr>
		<tr>
			<td ><strong>Employee Record #:</strong></td>
			<td >" . $form_data['emp_record_num'] . "</td>
		</tr>
		<tr>
			<td ><strong>Union Code:</strong></td>
			<td >" . $form_data['union_code'] ."</td>
		</tr>
		<tr>
			<td ><strong>Primary Job Code:</strong></td>
			<td >" . $form_data['primary_job_code'] . "</td>
		</tr>
		<tr>
			<td ><strong>Current Pay Rate:</strong></td>
			<td >" . $form_data['current_pay_rate'] ."</td>
		</tr>
		<tr>
			<td ><strong>Additional Work Job Code:</strong></td>
			<td >" . $form_data['addl_work_job_code'] . "</td>
		</tr>
		<tr>
			<td ><strong>Additional Work Pay Rate:</strong></td>
			<td >" . $form_data['addl_work_pay_rate'] ."</td>
		</tr>
		<tr>
			<td ><strong>Total Dollars:</strong></td>
			<td >" . $form_data['total_dollars'] . "</td>
		</tr>
		<tr>
			<td ><strong>FAO:</strong></td>
			<td >" . $form_data['fao'] . "</td>
		</tr>";
}
		$email_body .= "<tr style='background-color:gray;'><td colspan='2'>&nbsp;<!-- spacer -->&nbsp;</td></tr>
		</table><br/>";		
		
	// ========================================================================================
	// EMAIL LINK TO APPROVAL FORM
	// ======================================================================================== 		
	$biz_mgr_approval_link = "<p>To approve or deny this request, you must access the approval form by clicking on the link below.<br/>		 
	<a href='http://www.facilities.rochester.edu/_forms/additional_pay/response.php?id=$reqID&who=mgr'>ONLINE APPROVAL FORM</a></p><br/>";
	$admin_approval_link = "<p>To complete this form, you must access it by clicking on the link below.<br/>		 
	<a href='http://www.facilities.rochester.edu/_forms/additional_pay/response.php?id=$reqID&who=admin'>ONLINE APPROVAL FORM</a></p><br/>";
	
	// ========================================================================================
	// EMAIL BOTTOM
	// ========================================================================================  	
	$email_end = "</body></html>";
	 	
?>